apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  labels:
    app: grafana-app
  namespace: K8s-Monitoring-Namespace  # change
  annotations:
    developer/name: "Mislav Jakšić"
    developer/email: "jaksicmislav@gmail.com"
    developer/url: "https://github.com/MislavJaksic"
    developer/role: "technical lead"
    developer/timezone: "Europe/Zagreb"
    developer/picUrl: "https://images.app.goo.gl/PCHZgd8oattge1i96"
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: grafana-tier
  template:
    metadata:
      labels:
        tier: grafana-tier
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:6.2.5
        env:
          # - name: "GF_<SectionName>_<KeyName>"  # override settings with ENV VARs
          #   value: ""
          # - name: "GF_AUTH_ANONYMOUS_ENABLED"  # view dashboards without login
          #   value: "true"
          # - name: "GF_AUTH_ANONYMOUS_ORG_NAME"
          #   value: "DataFlux"
          # - name: "GF_AUTH_ANONYMOUS_ORG_ROLE"
          #   value: "Admin"
          # - name: "GF_SECURITY_ALLOW_EMBEDDING"  # can embbed links
          #   value: "true"
        ports:
        - name: grafana
          containerPort: 3000
          protocol: TCP
        volumeMounts:
        - name: grafana-data
          mountPath: /var/lib/grafana
        - name: grafana-logs
          mountPath: /var/log/grafana
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20
      volumes:
      - name: grafana-data
        emptyDir: {}
      - name: grafana-logs
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  labels:
    app: grafana-service-app
  namespace: K8s-Monitoring-Namespace  # change
  annotations:
    developer/name: "Mislav Jakšić"
    developer/email: "jaksicmislav@gmail.com"
    developer/url: "https://github.com/MislavJaksic"
    developer/role: "technical lead"
    developer/timezone: "Europe/Zagreb"
    developer/picUrl: "https://images.app.goo.gl/PCHZgd8oattge1i96"
spec:
  ports:
  - name: grafana
    nodePort: 30901
    targetPort: 3000
    port: 3000
    protocol: TCP
  selector:
    tier: grafana-tier
  type: NodePort
