apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: Plural-Name.Group-Name  # change
spec:
  group: Group-Name  # change
  versions:
    - name: v1
      served: true
      storage: true  # only one version can be `true`
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                stringFieldName:  # change
                  type: string
                replicas:
                  type: integer
  scope: Namespaced  # `Namespaced` or `Cluster`
  names:
    plural: Plural-Name  # change
    singular: Singular-Name  # change
    kind: CamelCased-Singular-Name  # change; used by manifests
    shortNames:
    - Short-Name-Alias  # change
