apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: jaeger-service-monitor
  labels:
    monitor: Prometheus-Monitor-Label  # change
  namespace: K8s-Tracing-Namespace  # change
  annotations:
    developer/name: "Mislav Jakšić"
    developer/email: "jaksicmislav@gmail.com"
    developer/url: "https://github.com/MislavJaksic"
    developer/role: "technical lead"
    developer/timezone: "Europe/Zagreb"
    developer/picUrl: "https://images.app.goo.gl/PCHZgd8oattge1i96"
spec:
  selector:
    matchLabels:
      name: jaeger-operator
  namespaceSelector:
    matchNames:
      - K8s-Tracing-Namespace  # change
  endpoints:
  - port: http-metrics
