apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: testcrdhelms.test.crd  # change
spec:
  group: test.crd  # change
  versions:
    - name: v1
      served: true
      storage: true  # only one version can be `true`
  scope: Namespaced  # `Namespaced` or `Cluster`
  names:
    plural: testcrdhelms  # change
    singular: testcrdhelm  # change
    kind: TestCrdHelm  # change; used by manifests
    shortNames:
    - tch  # change
  preserveUnknownFields: false
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            number:  # change
              type: string
            replicas:
              type: integer

