apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: argocd-mapping
  labels:
    app: argocd-mapping-app
  namespace: K8s-Ambassador-Namespace  # change
  annotations:
    developer/name: "Mislav Jakšić"
    developer/email: "jaksicmislav@gmail.com"
    developer/url: "https://github.com/MislavJaksic"
    developer/role: "technical lead"
    developer/timezone: "Europe/Zagreb"
    developer/picUrl: "https://images.app.goo.gl/PCHZgd8oattge1i96"
spec:
  prefix: /Http-Path/  # same as command argocd-server's --rootpath
  service: 'argocd-server.K8s-Argocd-Namespace'  # [Scheme://]Service-Name[.Namespace][:Port]
  rewrite: /Http-Path/  # same as command argocd-server's --rootpath
