apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  labels:
    app: prometheus-app
  namespace: K8s-Monitoring-Namespace  # change
  annotations:
    developer/name: "Mislav Jakšić"
    developer/email: "jaksicmislav@gmail.com"
    developer/url: "https://github.com/MislavJaksic"
    developer/role: "technical lead"
    developer/timezone: "Europe/Zagreb"
    developer/picUrl: "https://images.app.goo.gl/PCHZgd8oattge1i96"
spec:
  serviceAccountName: prometheus
  serviceMonitorSelector:  # monitor through Services
    matchLabels:
      monitor: Prometheus-Monitor-Label  # change
  # podMonitorSelector:  # monitor through Pods
  #   matchLabels:
  #     monitor: Prometheus-Monitor-Label  # change
  # ruleSelector:  # select rules
  #   matchLabels:
  #     rule: Prometheus-Rule-Label  # change
  # alerting:  # alert
  #   alertmanagers:
  #   - namespace: K8s-Monitoring-Namespace  # change
  #     name: alertmanager
  #     port: alertmanager
  # additionalScrapeConfigs:  # input config
  #   name: additional-scrape-configs
  #   key: prometheus-additional.yaml
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: false  # enable Admin API
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  labels:
    app: prometheus-service-app
  namespace: K8s-Monitoring-Namespace  # change
  annotations:
    developer/name: "Mislav Jakšić"
    developer/email: "jaksicmislav@gmail.com"
    developer/url: "https://github.com/MislavJaksic"
    developer/role: "technical lead"
    developer/timezone: "Europe/Zagreb"
    developer/picUrl: "https://images.app.goo.gl/PCHZgd8oattge1i96"
spec:
  type: NodePort
  ports:
  - name: web
    nodePort: 30900
    port: 9090
    protocol: TCP
  selector:
    prometheus: prometheus  # don't change!
