apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  namespace: K8-Namespace  # change
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle  # only NFS and HostPath support recycling
  nfs:
    path: /mnt/nfs
    server: Nfs-Server-Ip  # change
