apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: {{ .Values.elasticClusterName }}  # change
  labels:
    app: {{ .Values.elasticClusterName }}-app  # change
  namespace: {{ .Values.kubernetesElasticNamespace }}  # change
  annotations:
    developer/name: "Mislav Jakšić"
    developer/email: "jaksicmislav@gmail.com"
    developer/url: "https://github.com/MislavJaksic"
    developer/role: "technical lead"
    developer/timezone: "Europe/Zagreb"
    developer/picUrl: "https://images.app.goo.gl/PCHZgd8oattge1i96"
spec:
  version: 7.5.1
  http:
    service:
      spec:
        type: NodePort
        ports:
        - nodePort: 32000
          port: 9200
  nodeSets:
  - name: {{ .Values.elasticClusterName }}-name  # change
    count: 2
    config:
      node.master: true
      node.data: true
      node.ingest: true
      node.store.allow_mmap: false  # true for production!
    podTemplate:  # ephemeral!
      spec:
        volumes:
        - name: elasticsearch-data
          emptyDir: {}
        # - name: sysctl    # for production!
        #   securityContext:
        #     privileged: true
        #   command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
    # volumeClaimTemplates:  # persistent!
    # - metadata:
    #     name: elasticsearch-data
    #   spec:
    #     accessModes:
    #     - ReadWriteOnce
    #     resources:
    #       requests:
    #         storage: 1Gi
    #     storageClassName: Storage-Class-Name  # change
