apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: {{ .Values.kibanaClusterName }}  # change
  labels:
    app: {{ .Values.kibanaClusterName }}-app  # change
  namespace: {{ .Values.kubernetesElasticNamespace }}  # change
  annotations:
    developer/name: "Mislav Jakšić"
    developer/email: "jaksicmislav@gmail.com"
    developer/url: "https://github.com/MislavJaksic"
    developer/role: "technical lead"
    developer/timezone: "Europe/Zagreb"
    developer/picUrl: "https://images.app.goo.gl/PCHZgd8oattge1i96"
spec:
  version: 7.5.1
  count: 1
  elasticsearchRef:
    name: {{ .Values.elasticClusterName }}  # change
    namespace: {{ .Values.kubernetesElasticNamespace }}  # change
  http:
    service:
      spec:
        type: NodePort
        ports:
        - nodePort: 32001
          port: 5601
  # podTemplate:  # not supported as of 06.02.2020.
  #   spec:
  #     initContainers:
  #     - name: install-plugins
  #       command: ["sh", "-c", "bin/kibana-plugin", "install", "https://github.com/pjhampton/kibana-prometheus-exporter/releases/download/7.5.1/kibana-prometheus-exporter-7.5.1.zip"]
