apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: jaeger-service-monitor
  labels:
    name: jaeger-operator  # change
  namespace: K8s-Monitoring-Namespace  # change
spec:
  selector:
    matchLabels:
      name: jaeger-operator
  namespaceSelector:
    matchNames:
      - K8s-Tracing-Namespace  # change
  endpoints:
  - port: http-metrics
