apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: jaeger-query-mapping
  labels:
    app: jaeger-query-mapping-app
  namespace: K8s-Ambassador-Namespace  # change
  annotations:
    developer/name: "Mislav Jakšić"
    developer/email: "jaksicmislav@gmail.com"
    developer/url: "https://github.com/MislavJaksic"
    developer/role: "technical lead"
    developer/timezone: "Europe/Zagreb"
    developer/picUrl: "https://images.app.goo.gl/PCHZgd8oattge1i96"
spec:
  prefix: /jaeger/query/  # same as base-path
  service: 'simplest-query.K8s-Tracing-Namespace:16686'  # [Scheme://]Service-Name[.Namespace][:Port]
  rewrite: /jaeger/query/  # same as base-path
