apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotrod-deployment
  labels:
    app: hotrod-app
  namespace: K8s-Tracing-Namespace  # change
  annotations:
    developer/name: "Mislav Jakšić"
    developer/email: "jaksicmislav@gmail.com"
    developer/url: "https://github.com/MislavJaksic"
    developer/role: "technical lead"
    developer/timezone: "Europe/Zagreb"
    developer/picUrl: "https://images.app.goo.gl/PCHZgd8oattge1i96"
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: hotrod-tier
  template:
    metadata:
      labels:
        tier: hotrod-tier
    spec:
      containers:
      - name: jaeger-hotrod
        image: jaegertracing/example-hotrod:latest
        args: ["all"]
        env:
          - name: "JAEGER_AGENT_HOST"
            value: "simplest-agent"
          - name: "JAEGER_AGENT_PORT"
            value: "6831"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: hotrod-service
  labels:
    app: hotrod-service-app
  namespace: K8s-Tracing-Namespace  # change
  annotations:
    developer/name: "Mislav Jakšić"
    developer/email: "jaksicmislav@gmail.com"
    developer/url: "https://github.com/MislavJaksic"
    developer/role: "technical lead"
    developer/timezone: "Europe/Zagreb"
    developer/picUrl: "https://images.app.goo.gl/PCHZgd8oattge1i96"
spec:
  type: NodePort
  selector:
    tier: hotrod-tier
  ports:
  - port: 8080
    targetPort: 8080
