apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simplest
  labels:
    app: simplest-jaeger-app
  namespace: K8s-Tracing-Namespace  # change
  annotations:
    developer/name: "Mislav Jakšić"
    developer/email: "jaksicmislav@gmail.com"
    developer/url: "https://github.com/MislavJaksic"
    developer/role: "technical lead"
    developer/timezone: "Europe/Zagreb"
    developer/picUrl: "https://images.app.goo.gl/PCHZgd8oattge1i96"
spec:
  allInOne:
    options:
      query:
        base-path: /jaeger/query  # base path for all HTTP routes, for when running behind a proxy, an ingress
  # ingress:
  #   enabled: false  # don't create ingress rule
  #   secretName: my-tls-secret  # enable ingress TLS
