apiVersion: apps/v1
kind: Deployment
metadata:
  name: generator-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: generator-tier
  template:
    metadata:
      labels:
        tier: generator-tier
    spec:
      containers:
      - name: generator
        image: mj753951/generator:demo
        ports:
          - containerPort: 5001
        env:
          - name: "ADDRESS"
            value: "http://filter-service:5002/filter"
      restartPolicy: Always
