---
apiVersion: v1
kind: Service
metadata:
  name: ambassador
spec:
  type: NodePort/LoadBalancer/loadBalancerIP
  externalTrafficPolicy: Local
  ports:
   - port: 80
     targetPort: 8080
  selector:
    service: ambassador
