---
apiVersion: v1
kind: Service
metadata:
  name: ambassador
spec:
  type: Supported-Service-Type  # choose one
  externalTrafficPolicy: Local  # propagate the (request) source IP
  ports:
  - name: http  # may have different ports
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https  # may have different ports
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    service: ambassador
