apiVersion: apps/v1
kind: Deployment
metadata:
  name: Deployment-Name  # change
  labels:
    app: Deployment-App-Label  # change
  namespace: App-Namespace  # change
  annotations:
    developer/name: "Mislav Jakšić"
    developer/email: "jaksicmislav@gmail.com"
    developer/url: "https://github.com/MislavJaksic"
    developer/role: "technical lead"
    developer/timezone: "Europe/Zagreb"
    developer/picUrl: "https://images.app.goo.gl/PCHZgd8oattge1i96"
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: Tier-Label  # change
  template:
    metadata:
      labels:
        tier: Tier-Label  # change
    spec:
      containers:
      - name: example-app
        image: fabxc/instrumented_app
        ports:
        - name: Port-Name  # change
          containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: Service-Name  # change
  labels:
    app: Service-App-Label  # change
  namespace: App-Namespace  # change
  annotations:
    developer/name: "Mislav Jakšić"
    developer/email: "jaksicmislav@gmail.com"
    developer/url: "https://github.com/MislavJaksic"
    developer/role: "technical lead"
    developer/timezone: "Europe/Zagreb"
    developer/picUrl: "https://images.app.goo.gl/PCHZgd8oattge1i96"
spec:
  selector:
    tier: Tier-Label  # change
  ports:
  - name: Port-Name  # change
    port: 8080
