apiVersion: apps/v1
kind: Deployment
metadata:
  name: Deployment-Name  # change
  namespace: App-Namespace  # change
spec:
  replicas: 3
  selector:
    matchLabels:
      app: App-Label  # change
  template:
    metadata:
      labels:
        app: App-Label  # change
    spec:
      containers:
      - name: example-app
        image: fabxc/instrumented_app
        ports:
        - name: Port-Name  # change
          containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: Service-Name  # change
  namespace: App-Namespace  # change
spec:
  selector:
    app: App-Label  # change
  ports:
  - name: Port-Name  # change
    port: 8080
