apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      monitor: Monitor-Label  # change
  # podMonitorSelector:
  #   matchLabels:
  #     monitor: Monitor-Label  # change
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: false  # enable Admin API
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  type: NodePort
  ports:
  - name: web
    nodePort: 30900
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    prometheus: prometheus
