apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  labels:
    app: prometheus-app
  namespace: K8s-Monitoring-Namespace  # change
  annotations:
    developer/name: "Mislav Jakšić"
    developer/email: "jaksicmislav@gmail.com"
    developer/url: "https://github.com/MislavJaksic"
    developer/role: "technical lead"
    developer/timezone: "Europe/Zagreb"
    developer/picUrl: "https://images.app.goo.gl/PCHZgd8oattge1i96"
spec:
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      monitor: Prometheus-Monitor-Label  # change
  # podMonitorSelector:
  #   matchLabels:
  #     monitor: Prometheus-Monitor-Label  # change
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: false  # enable Admin API
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus-service-app
  namespace: K8s-Monitoring-Namespace  # change
  annotations:
    developer/name: "Mislav Jakšić"
    developer/email: "jaksicmislav@gmail.com"
    developer/url: "https://github.com/MislavJaksic"
    developer/role: "technical lead"
    developer/timezone: "Europe/Zagreb"
    developer/picUrl: "https://images.app.goo.gl/PCHZgd8oattge1i96"
spec:
  type: NodePort
  ports:
  - name: web
    nodePort: 30900
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    prometheus: prometheus
